from pydantic import BaseModel, Field

class AgentRequest(BaseModel):
    session_id: str = Field(..., description="Unique ID to distinguish the conversation session")
    prompt: str = Field(..., description="User input or in-game event")

class AgentResponse(BaseModel):
    session_id: str
    # action: str = Field(..., description="Action determined by the AI agent")
    response_text: str = Field(..., description="Response text generated by the AI")